### ISSUE TITLE
Messenger - Allow for adding nickname groupings

### ISSUE THREAD

**Issue by no-trick-pony** [RavuAlHemio/SharpIrcBot#7]
As many folks make use of multiple nicks (not grouped nicks but multiple registrations) I want to suggest the following feature:

Trustworthy users (like channel OPs) can group nicknames by specifying them as a list. The grouped nicknames can then be used synonymously regarding the messaging system.

Consider the following example: A user has two accounts: Schlapf and Schlapf|mobile. Sending a message to Schlapf|mobile is of course intented for the user not the specific account. However, Schlapf will never receive a message sent to Schlapf|mobile.

To change this behaviour, one could introduce a `!group` command which lets some trustworthy user (referred to as "no schlapfs") group these nicks, like so: `!group Schlapf Schlapf|mobile`. Single users could also be implemented as groups with only one member per default, making `!group` simply a command that groups multiple existing groups into one. After a "no schlapf" has grouped the nicks of  Schlapf, the example above will work and Schlapf will receive his certainly extremely important message even though it had been sent to Schlapf|mobile.

**Comment by RavuAlHemio** [comment]
As much as I would prefer people simply registering with NickServ and linking their accounts together (using the `GROUP` command), I guess I'm fighting an uphill battle here.

I think it makes sense to implement some form of central infrastructure for nickname linking, since multiple plugins (e.g. Messenger and Thanks) can profit from it.

**Comment by RavuAlHemio** [comment]
The feature should work now. You might be interested in the [command reference](https://github.com/RavuAlHemio/SharpIrcBot/wiki/AvailableCommands#databasenickmappingplugin).
